/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "elrsiotacvvtvurciugf"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVscnNpb3RhY3Z2dHZ1cmNpdWdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA0OTU5MzIsImV4cCI6MjA4NjA3MTkzMn0.tkaZDLh9QgQDW3gmJqav-cMy25WjlTzqKzSeEIEJno0"
